# DB
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://211.119.65.82:3306/icms?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: icms
    password: "icms#123"

# server
server:
  port: 8080

# dataSourceConfig
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  config-location: classpath:/mybatis-config.xml
  type-aliases-package: com.study.skeletonPj.api.**.domain

#swagger
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

# project
skeleton_project:
  openapi:
    dev-url: http://localhost:8080
    prod-url: http://localhost:8080